name: Build and Test

on:      
  push:
    branches:
      - development
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**.md'
      - '**.mm'
  pull_request:
    branches:
      - development
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**.md'
      - '**.mm'
      
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: palette.flatpak
        manifest-path: org.gnome.zbrown.Palette.yml
        cache-key: flatpak-builder-${{ github.sha }}

    # Build the Flatpak application
    - name: Build Flatpak application
      run: |
        flatpak-builder --user --install-deps-from=flathub build-dir io.github.louis77.tuner.yml

    # Verify the Flatpak application
    - name: Verify Flatpak build
      run: |
        flatpak-builder --run build-dir io.github.louis77.tuner.yml tuner --version
